version: "{build}"

os: Visual Studio 2015

platform: 
  - Win32

environment:  
  global:
    MSVC_DEFAULT_OPTIONS: ON
    BOOST_ROOT: "C:\\Libraries\\boost_1_63_0"
    BOOST_LIBRARYDIR: "%BOOST_ROOT%\\lib32-msvc-14.0"
    ZLIB_DIR: "%APPVEYOR_BUILD_FOLDER%\\zlib-1.2.11"

  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      
install:
  - "cd C:\\OpenSSL-Win32"
  - dir
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - cd %APPVEYOR_BUILD_FOLDER%
  - ps: Start-FileDownload "http://zlib.net/zlib1211.zip" -FileName zlib.zip
  - 7z x zlib.zip -y
  - cd %ZLIB_DIR%
  - cmake .

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - python setup.py build --open-ssl-dir="C:\OpenSSL-Win32"

test_script:
  - python setup.py test
