version: "{build}"

os: Visual Studio 2015

configuration: Release

environment:
  global:
    MSVC_DEFAULT_OPTIONS: ON
    BOOST_ROOT: "C:\\Libraries\\boost_1_63_0"

  matrix:
    - PYTHON_VERSION: "3.5"
      platform: x86
      PYTHON: "C:\\Python35"
      BOOST_LIBRARYDIR: "%BOOST_ROOT%\\lib32-msvc-14.0"
      OPENSSL_ROOT_DIR: "C:\\OpenSSL-Win32"

    - PYTHON_VERSION: "3.5"
      platform: x64
      PYTHON: "C:\\Python35-x64"
      BOOST_LIBRARYDIR: "%BOOST_ROOT%\\lib64-msvc-14.0"
      OPENSSL_ROOT_DIR: "C:\\OpenSSL-Win64"

    - PYTHON_VERSION: "3.6"
      platform: x86
      PYTHON: "C:\\Python36"
      BOOST_LIBRARYDIR: "%BOOST_ROOT%\\lib32-msvc-14.0"
      OPENSSL_ROOT_DIR: "C:\\OpenSSL-Win32"

    - PYTHON_VERSION: "3.6"
      platform: x64
      PYTHON: "C:\\Python36-x64"
      BOOST_LIBRARYDIR: "%BOOST_ROOT%\\lib64-msvc-14.0"
      OPENSSL_ROOT_DIR: "C:\\OpenSSL-Win64"

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;OPENSSL_ROOT_DIR\\bin;%PATH%"
  - python --version
  - pip --version
  - openssl version
  - dir "%OPENSSL_ROOT_DIR%\\lib\\VC\\static"
  - pip install wheel

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - python setup.py build

test_script:
  - python setup.py test

after_test:
  - python setup.py bdist_wheel

artifacts:
  - path: dist\*.whl

deploy:
  tag: "%APPVEYOR_REPO_TAG_NAME%"
  description: "WsgiBoostServer %APPVEYOR_REPO_TAG_NAME%"
  provider: GitHub
  auth_token:
    secure: Re1VQJJUIe8Dlcz5Ug34e0VY4ySc8+l0nluwWkJ+LC/XxZIAUSmDU5i0rmPExjoi
  artifact: /.*\.whl/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
