version: "{build}"

os: Visual Studio 2015

platform: 
  - Win32

environment:  
  global:
    MSVC_DEFAULT_OPTIONS: ON
    BOOST_ROOT: "%APPVEYOR_BUILD_FOLDER%\\boost"
    BOOST_LIBRARYDIR: "%BOOST_ROOT%\\stage\\lib"
    ZLIB_DIR: "%APPVEYOR_BUILD_FOLDER%\\zlib-1.2.11"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      
install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - cd %APPVEYOR_BUILD_FOLDER%
  - ps: Start-FileDownload "http://zlib.net/zlib1211.zip" -FileName zlib.zip
  - 7z x zlib.zip -y
  - cd %ZLIB_DIR%
  - cmake .
  - cd %APPVEYOR_BUILD_FOLDER%
  - "git clone https://github.com/romanvm/boost.git"
  - python appveyor.py
  - cd %BOOST_ROOT%
  - bootstrap.bat
  - "b2 -j2 link=static runtime-link=static variant=release -sZLIB_SOURCE=%ZLIB_DIR% --with-regex --with-system --with-coroutine --with-context --with-filesystem --with-iostreams --with-date_time --with-python"

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - python setup.py build

test_script:
  - python setup.py test
